### ISSUE TITLE
Error "[E::idx_find_and_load] Could not retrieve index file

### ISSUE THREAD

**Issue by JHCCoder** [haessar/peaks2utr#14]
Hi Haessar, 

Every run of peaks2utr I have, including the run from the demo, has these message in the run log:
[E::idx_find_and_load] Could not retrieve index file for '/home/jhc103/code/rosetta-stone-proj/peaks2utr-demo/.cache/Tb927_01_v5.1.slice.forward.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/jhc103/code/rosetta-stone-proj/peaks2utr-demo/.cache/Tb927_01_v5.1.slice.reverse.bam'

Is this expected behavior? I am running version 0.5.1. I did not switch to the latest peaks2utr because I was not able to get those versions to work on my files. 

Best

**Comment by haessar** [comment]
See discussion here https://github.com/pysam-developers/pysam/issues/939
This is coming directly from pysam because I am not indexing the forward/reverse stranded bam files (have no need to and will just increase run time). As alluded to in the above issue, I can either fix pysam to the earlier version 0.15.3 where this check doesn't take place (which I'm reluctant to do), implement the python workaround as suggested to suppress the warning, or just index the files anyway. I will explore the latter two options.

**Comment by JHCCoder** [comment]
Got it thank you
