### ISSUE TITLE
'colour' variable added to GTF files

### ISSUE THREAD

**Issue by alishamay1305** [haessar/peaks2utr#26]
Hello,

I have run peaks2utr to improve the 3'UTR annotation of the Japanese quail genome, and I always use the -gtf flag to get a GTF file output. When I open the GTF file output as a data frame in Rstudio, I noticed that an extra variable 'colour' has been added, what exactly is this?

Thank you in advance!

**Comment by haessar** [comment]
Hi, thanks for getting in touch. The colour attribute allows genome visualisers to display the annotations using various colours. You can see what each of these numeric values maps to in Artemis [here](https://github.com/haessar/peaks2utr/blob/f93d49465810a3313d7fc0444bbc8e2ddaf0ddc0/peaks2utr/constants.py#L5).

Is it causing issues with your downstream analysis? (i.e. throwing an error because another tool can't parse it). If so, I can explore making it an optional thing.

**Comment by alishamay1305** [comment]
Hi, thanks for such a quick reply! Okay I understand.

It hasn't caused any issues, I was just curious, thanks again!
