### ISSUE TITLE
Warning message: Genometools binary can't be called

### ISSUE THREAD

**Issue by jpiggod** [haessar/peaks2utr#3]
I got a warning message saying that "Genometools binary" can't be called but I couldn't find the log file `gt_gff3.log` in the directory where I executed the run. From the warning message, it's a bit obscure whether anything wrong has happened or not:

```
2023-01-31 15:58:13,954 - INFO - Finished calling reverse strand peaks.
2023-01-31 16:03:12,669 - INFO - Finished calling forward strand peaks.
INFO     Iterating over peaks to annotate 3' UTRs.: 535600it [04:29, 1986.50it/s]
2023-01-31 16:07:44,183 - INFO - Merging annotations with canonical gff file.
2023-01-31 16:07:45,163 - WARNING - Genometools binary can't be called. Please ensure it is installed.
2023-01-31 16:07:45,164 - WARNING - Some issues were encountered when processing output file. Check gt_gff3.log.
2023-01-31 16:07:45,172 - INFO - Writing summary statistics file.
2023-01-31 16:07:46,109 - INFO - peaks2utr finished successfully.
2023-01-31 16:07:47,112 - INFO - Clearing cache.
```
(For brevity, I only showed the relevant parts here. No warning messages elsewhere during the run.)

Let me show more details about the run:
- Initially, I actually used a file in `gtf` format (rather than `gff`) and I thought the warning message could have arisen because of the format incompatibility. So I went to convert my `gtf` file to `gff3` and ran `peaks2utr` again, but the warning message persisted.
- I deal with a non-model organism and the single-cell dataset is not published yet, so I'm afraid I can't reveal here which dataset I was running. The genome annotation file is from ensembl. 
- I performed the run via a conda virtual environment (with only `peaks2utr` and other necessary packages such as `pandas` installed) on a linux server.

Thank you so much!

**Comment by haessar** [comment]
During post-processing there is an attempt to call a genometools binary on the users system as a subprocess in order to sort / tidy the final output (i.e. "gt gff3 -sort -retainids -tidy FILE", if you're familiar with genometools). The reason for incorporating this step was because it's a fairly standard procedure when handling gff3 files amongst bioinformaticians, and there is an expectation that many users will have this binary available on their path.

When the binary isn't detected (as in your case) the output file "file.new.gff3" will just be the peaks2utr output without this genometools treatment, which should still be valid (but perhaps not sorted) - therefore it's safe to ignore this error.

As for the location of the gt_gff3.log file, there should be a ".log/" directory located in the directory where you ran peaks2utr (note the "." prefix - this might be hidden in your file explorer).

**Comment by haessar** [comment]
Added instruction to README for installing genometools dependency in release https://github.com/haessar/peaks2utr/releases/tag/v0.4
